// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CsService_Request_FullMethodName = "/CsService/Request"
)

// CsServiceClient is the client API for CsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CsServiceClient interface {
	Request(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
}

type csServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCsServiceClient(cc grpc.ClientConnInterface) CsServiceClient {
	return &csServiceClient{cc}
}

func (c *csServiceClient) Request(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, CsService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CsServiceServer is the server API for CsService service.
// All implementations must embed UnimplementedCsServiceServer
// for forward compatibility.
type CsServiceServer interface {
	Request(context.Context, *NodeRequest) (*NodeResponse, error)
	mustEmbedUnimplementedCsServiceServer()
}

// UnimplementedCsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCsServiceServer struct{}

func (UnimplementedCsServiceServer) Request(context.Context, *NodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedCsServiceServer) mustEmbedUnimplementedCsServiceServer() {}
func (UnimplementedCsServiceServer) testEmbeddedByValue()                   {}

// UnsafeCsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CsServiceServer will
// result in compilation errors.
type UnsafeCsServiceServer interface {
	mustEmbedUnimplementedCsServiceServer()
}

func RegisterCsServiceServer(s grpc.ServiceRegistrar, srv CsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CsService_ServiceDesc, srv)
}

func _CsService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CsService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsServiceServer).Request(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CsService_ServiceDesc is the grpc.ServiceDesc for CsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CsService",
	HandlerType: (*CsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _CsService_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
